### ISSUE TITLE
[ Inacurate ] Lateral Movement Tactic:  T1051 From Website & Different CTI Github | Enterprise Matrix

### ISSUE THREAD

**Issue by dfirence** [mitre/cti#102]
I just downloaded your enterprise matrix.

IS T1051 to be accurately counted in **lateral-movement**? (Y/N)

This is affecting accurate reporting on my side.  I have **10 unique techniques** for lateral movement.

Your website shows count of 9 Techniques for Lateral Movement:  [HERE](https://user-images.githubusercontent.com/11415591/89735299-851fe700-da2f-11ea-86da-fc8a647a6f87.png)

Therefore, **T1051 - Shared Webroot** is missing from your Website.

<br/>

**What is the accurate status for T1051?**

<br/>

**Do we account for it, or will it be revoked?**

<br/>
<br/>

## Website View
![image](https://user-images.githubusercontent.com/11415591/89735299-851fe700-da2f-11ea-86da-fc8a647a6f87.png)

<br/>
<br/>

## CTI Github has it

![image](https://user-images.githubusercontent.com/11415591/89735313-a1238880-da2f-11ea-9c48-70473d795471.png)

```
![image](https://user-images.githubusercontent.com/11415591/89735314-a2ed4c00-da2f-11ea-8771-0ff2634bc331.png)
```

<br/>
<br/>

## Counts of Tactic

![image](https://user-images.githubusercontent.com/11415591/89735348-e8aa1480-da2f-11ea-89df-34cbed6af272.png)

```
![image](https://user-images.githubusercontent.com/11415591/89735347-e6e05100-da2f-11ea-95f0-1f756eecee43.png)

```

**Comment by isaisabel** [comment]
Shared Webroot is deprecated and therefore does not appear on the website. Please see [Working with deprecated and revoked objects](https://github.com/mitre/cti/blob/master/USAGE.md#working-with-deprecated-and-revoked-objects) in our USAGE document for more information.
