### ISSUE TITLE
502 Server Error: Bad Gateway for url: https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/

### ISSUE THREAD

**Issue by csmarti** [mitre/cti#107]
I also hit this same error when trying to instantiate a server object connecting to the top level taxii endpoint at https://cti-taxii.mitre.org/taxii/. I was receiving content back from the server this morning, as recently as 2 hours ago.
![image](https://user-images.githubusercontent.com/70949003/92467167-0a322380-f1c9-11ea-8696-0a1b61c49953.png)

**Comment by isaisabel** [comment]
Hi @csmarti,

Sorry, the TAXII server had an outage this morning. It should be back online now.
