### ISSUE TITLE
Standardise descriptions of "mitigates" relationships in enterprise-attack.json

### ISSUE THREAD

**Issue by grimlock81** [mitre/cti#109]
I had a task of processing enterprise-attack.json to extract the set of unique descriptions for the relationship where 

- relationship_type="mitigates"
- source_ref starts with "course-of-action"
- target_ref starts with "attack-pattern"

in other words the relationships describing "Mitigation mitigating technique"

I found that there were instances of relationships which had similar descriptions that only differed slightly. In most cases it was due to extra whitespace or punctuation, in other cases the same information was slightly reformatted or reworded.

For example for the Mitigation "User Training" (M1017), the description for the use on techniques 1547.007 and 1547.011 are essentially the same but they differ in the case of the word "Shift/shift" as well as "while logging in/during login". Is there any reason for the discrepancy?
![](https://i.imgur.com/ngsiBBM.png)

This screenshot is from the webpage but the discrepancy is also present in the JSON

```json
{
	"created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
	"object_marking_refs": [
		"marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
	],
	"source_ref": "course-of-action--2a4f6c11-a4a7-4cb9-b0ef-6ae1bb3a718a",
	"target_ref": "attack-pattern--e5cc9e7a-e61a-46a1-b869-55fb6eab058e",
	"relationship_type": "mitigates",
	"description": "Holding the Shift key while logging in prevents apps from opening automatically. (Citation: Re-Open windows on Mac)",
	"id": "relationship--f5499769-be56-4995-b993-0a2bc59a0f08",
	"external_references": [
		{
			"url": "https://support.apple.com/en-us/HT204005",
			"description": "Apple. (2016, December 6). Automatically re-open windows, apps, and documents on your Mac. Retrieved July 11, 2017.",
			"source_name": "Re-Open windows on Mac"
		}
	],
	"type": "relationship",
	"modified": "2020-01-24T19:51:37.952Z",
	"created": "2020-01-24T18:15:06.946Z"
},
```

```json
	"created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
	"object_marking_refs": [
		"marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
	],
	"source_ref": "course-of-action--2a4f6c11-a4a7-4cb9-b0ef-6ae1bb3a718a",
	"target_ref": "attack-pattern--6747daa2-3533-4e78-8fb8-446ebb86448a",
	"relationship_type": "mitigates",
	"description": "Holding the shift key during login prevents apps from opening automatically. (Citation: Re-Open windows on Mac)",
	"id": "relationship--5bd0885d-7511-4e6b-b68d-f77bed9584a2",
	"external_references": [
		{
			"url": "https://support.apple.com/en-us/HT204005",
			"description": "Apple. (2016, December 6). Automatically re-open windows, apps, and documents on your Mac. Retrieved July 11, 2017.",
			"source_name": "Re-Open windows on Mac"
		}
	],
	"type": "relationship",
	"modified": "2020-06-20T19:57:36.323Z",
	"created": "2020-03-19T19:17:21.370Z"
},
```

Another example is in the Mitigation "Operating System Configuration" (M1028). The description of the use against "Account Discovery (T1087) is

> Prevent administrator accounts from being enumerated when an application is elevating through UAC since it can lead to the disclosure of account names. The Registry key is located <code>HKLM\ SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\CredUI\EnumerateAdministrators</code>. It can be disabled through GPO: Computer Configuration > [Policies] > Administrative Templates > Windows Components > Credential User Interface: E numerate administrator accounts on elevation. (Citation: UCF STIG Elevation Account Enumeration)

while the description of the uses against "Local Account" (T1087.001) and "Domain Account" (T1087.002) is

> Prevent administrator accounts from being enumerated when an application is elevating through UAC since it can lead to the disclosure of account names. The Registry key is located at <code>HKLM\ SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\CredUI\EnumerateAdministrators</code>. It can be disabled through GPO: Computer Configuration > [Policies] > Administrative Templates > Windows Components > Credential User Interface: Enumerate administrator accounts on elevation.(Citation: UCF STIG Elevation Account Enumeration)

There are two differences here: 

1. The latter has the word 'at' just before the registry path, 
2. The former has a space after the 'E' in "Credential User Interface: Enumerate"

Is it possible to standardise these descriptions so that the entries that mean the same thing have the exact same content? I am prepared to compile a list of discrepancies if there is a chance that this will be addressed.

Thanks.

**Comment by isaisabel** [comment]
Hi @grimlock81,

Thank you for pointing out this discrepancy. Could you please resubmit this as an email to the attack mailbox (attack@mitre.org)? The content writing team doesn't use this issue tracker, it's mostly used for questions/comments/bugs regarding the formatting of the data and not the ATT&CK catalog content.

Thanks!

**Comment by grimlock81** [comment]
Thanks @isaisabel I will send via email.
