### ISSUE TITLE
Error creating Jira issue for T1205.001

### ISSUE THREAD

**Issue by FMarius** [mitre/cti#110]
Hello people, 
On my personal jira account I could create the project, but on my work environment I get this error: 
"Error creating Jira issue for T1205.001"
Could someone please advise ?
Many thanks! 
Marius

**Comment by isaisabel** [comment]
Hi @FMarius,

I'm a bit confused about your issue. This repository doesn't have any built-in Jira integration, and nor does any other component of the [ATT&CK infrastructure](https://github.com/mitre-attack). 

Anyway, the best I can do is tell you that T1205.001 is the technique ID for [Traffic Signaling: Port Knocking](https://attack.mitre.org/techniques/T1205/001/).

**Comment by FMarius** [comment]
Hello @isaisabel, 
Thank you for your response. I will look into it.
Marius
