### ISSUE TITLE
last_seen and first_seen on attackers and campaigns

### ISSUE THREAD

**Issue by sparrow-k** [mitre/cti#114]
Hello!
I was working with the server's data, and I couldn't find any intrusion-sets (groups) that has the optional attribute of last_seen, in order to query results by date. Code:
```
all_groups = enterprise_src.query([Filter("type", "=", "intrusion-set")])
for gr in all_groups:
    try:
        print(gr['last_seen'])
        print(gr["id"])
    except KeyError as e:
        pass
```

I then tried to query the campaigns themselves, and use them to build a last_seen date, but I noticed there weren't any campaigns objects in the DB either. Code:
`cam = enterprise_src.query([Filter("type", "=", "campaign")])`

Am I doing something wrong, or does the db simply doesn't have that information?
And if it doesn't, will it ever be added?

**Comment by isaisabel** [comment]
Hi @sparrow-k,

Firstly, my apologies for not responding sooner. I must've missed this when it was submitted originally.

Anyway, you're correct that we don't track `first_seen` or `last_seen` for groups (`intrusion-set`s). We also don't use `campaign` objects at present. It is unlikely that we'll add first and last seen for groups and I'm not sure if campaigns will eventually be added to the dataset either.
