### ISSUE TITLE
Consult:  V8 Enterprise Platforms: Meaning or Type for Value **PRE**

### ISSUE THREAD

**Issue by dfirence** [mitre/cti#117]
I am picking up 2 new platforms with the release of V8

**1** PRE

**2** NETWORK

<br/>

What is the **PRE** platform, please?

<br/>

The enterprise json MD5 I downloaded today is

 > md5sum ~/.mitre-assistant/matrixes/*
893241dec9ad51d32f36501e9efbab4d  /home/alice/mitre-assistant/matrixes/enterprise_V8.json
ddc480ed343ab646d9e47608e1a385ab  /home/alice/mitre-assistant/matrixes/enterprise_v7.json

<br/>
<br/>

![DC37257E-D633-446F-ABDE-1E5FA3500DC6](https://user-images.githubusercontent.com/11415591/97382078-efaf2900-18a0-11eb-9f93-4c84e8f371fb.jpeg)

**Comment by grimlock81** [comment]
It's explained here in the Updates: https://attack.mitre.org/resources/updates/updates-october-2020/index.html

> This release deprecates and removes the PRE-ATT&CK domain from ATT&CK, replacing its scope with two new Tactics in Enterprise ATT&CK [Reconnaissance](https://attack.mitre.org/tactics/TA0043/) and [Resource Development](https://attack.mitre.org/tactics/TA0042/). A new platform has also been added to ATT&CK to represent the environment these techniques occur in, [PRE](https://attack.mitre.org/matrices/enterprise/pre/). The previous contents of PRE-ATT&CK have been preserved [here](https://attack.mitre.org/versions/v7/matrices/pre/). See [the accompanying blog post](https://medium.com/mitre-attack/the-retirement-of-pre-attack-4b73ffecd3d3) for more details.

**Comment by isaisabel** [comment]
Yup, what @grimlock81 said is correct. The contents of this repo generally reflects what's on attack.mitre.org (with the exception of the ICS data, which is on http://collaborate.mitre.org/attackics/ until we migrate it over to the main site). Therefore further documentation about the nature of the content can generally be found over there.
