### ISSUE TITLE
Possible illegal reference id for S0154 in 56 relationship definitions

### ISSUE THREAD

**Issue by grimlock81** [mitre/cti#126]
In version 8.1, S0154 was changed from type `"tool"` to type `"malware"` and also the id changed from `"tool--aafea02e-ece5-4bb2-91a6-3bf8c7f38a39"` to `"malware--a7881f21-e978-4fe4-af56-92c9416a2616"`

However, there are still 56 relationships that refer to the old id `"tool--aafea02e-ece5-4bb2-91a6-3bf8c7f38a39"`. There is 1 (new) relationship that refers to the new id `"malware--a7881f21-e978-4fe4-af56-92c9416a2616"`

Is this an error? Should the 56 relationships now be pointing to the new id `"malware--a7881f21-e978-4fe4-af56-92c9416a2616"`? Or should I just ignore any ids in relationships that do not match up with any object in the JSON?

Thanks

Edit:
There's also another possible illegal reference id. For relationship `"relationship--3b3c27ed-0129-48bf-8c79-e86d73e5b212"`, the `target_ref` is `"tool--066b057c-944e-4cfc-b654-e3dfba04b926"` but I cannot find any other occurrences of this id in either 8.1 or 8.0.

**Comment by isaisabel** [comment]
Yes, both of these were errors. I patched them this morning: `relationship--3b3c27ed-0129-48bf-8c79-e86d73e5b212` was removed, and the prior relationships targeting S1054 were updated to point to its new ID.
