### ISSUE TITLE
‘x-mitre-matrix’ object for 'ICS' in the TAXII server is using the same object from 'Mobile' (different matrices but using the same id)

### ISSUE THREAD

**Issue by shawncxc** [mitre/cti#128]
I know the ICS collection is correct on Github, however the one on TAXII server is wrong, so submit a bug here just to get your attention.
The latest ICS collection on your TAXII server is different from your GitHub CTI repo: https://github.com/mitre/cti/blob/master/ics-attack/ics-attack.json
I believe the correct version is hosted on GitHub, the ‘x-mitre-matrix’ object in the TAXII server for ICS is using the same one from Mobile, please check and let us know, thanks.

**Comment by shawncxc** [comment]
Also, for technique 'Activate Firmware Update Mode' in ICS collection, there is a typo in the external ID, it should be 'T0800' instead of '0T800' (id: attack-pattern--19a71d1e-6334-4233-8260-b749cae37953)

**Comment by shawncxc** [comment]
I think the root cause is due to the 'x-mitre-matrix' object in ICS collection uses the same ID (x-mitre-matrix--a382db5e-d009-4135-b893-0e0ff021c95b) as the one in the Mobile collection, even though they are two different matrices.
Ideally, I believe the ID should be different, and I assume when you guys populating the TAXII server, it fetches the one from Mobile since they have the same ID

**Comment by isaisabel** [comment]
Thanks for reaching out. I'm 99% sure you're right about the ID collision being the cause, and we're going to issue a new ID to the ICS matrix (the ID collision was a mistake in the first place).

**Comment by isaisabel** [comment]
I'll also correct the incorrect technique ID while I'm at it.

**Comment by isaisabel** [comment]
The incorrect technique ID was only present in the master `ics-attack.json` bundle for what it's worth. In the individual object bundle it was fine. The TAXII server updates from the master bundle.

**Comment by isaisabel** [comment]
Should be fixed for the contents of this repo, TAXII server will be updating momentarily. I'll post an update here once it's complete and we've verified the fix worked.

**Comment by shawncxc** [comment]
Thanks, appreciate it!

**Comment by isaisabel** [comment]
TAXII server is returning the correct matrix now. Test code:
```
from stix2 import TAXIICollectionSource, Filter
from taxii2client.v20 import Server, Collection

collections = {
    "enterprise_attack": "95ecc380-afe9-11e4-9b6c-751b66dd541e",
    "pre_attack": "062767bd-02d2-4b72-84ba-56caef0f8658",
    "mobile_attack": "2f669986-b40b-4423-b720-4396ca6a462b",
    "ics": "02c3ef24-9cd4-48f3-a99f-b74ce24f1d34"
}

# check if the collection has the right matrix
collection = Collection(f"https://cti-taxii.mitre.org/stix/collections/{collections['ics']}/")
tc_src = TAXIICollectionSource(collection)
print(tc_src.query(
    Filter("type", "=", "x-mitre-matrix")
))
```

prints: 
```
[{'type': 'x-mitre-matrix', 'name': 'ATT&CK for ICS', 'description': 'The full ATT&CK for ICS Matrix includes techniques spanning various ICS assets and can be used to navigate through the knowledge base.', 'created_by_ref': 'identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5', 'created': '2018-10-17T00:14:20.652Z', 'id': 'x-mitre-matrix--575f48f4-8897-4468-897b-48bb364af6c7', 'modified': '2020-06-03T00:14:20.652Z', 'object_marking_refs': ['marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168'], 'external_references': [{'source_name': 'mitre-ics-attack', 'external_id': 'MA0010', 'url': 'https://collaborate.mitre.org/attackics/index.php/Main_Page'}], 'tactic_refs': ['x-mitre-tactic--69da72d2-f550-41c5-ab9e-e8255707f28a', 'x-mitre-tactic--93bf9a8e-b14c-4587-b6d5-9efc7c12eb45', 'x-mitre-tactic--78f1d2ae-a579-44c4-8fc5-3e1775c73fac', 'x-mitre-tactic--ddf70682-f3ce-479c-a9a4-7eadf9bfead7', 'x-mitre-tactic--696af733-728e-49d7-8261-75fdc590f453', 'x-mitre-tactic--51c25a9e-8615-40c0-8afd-1da578847924', 'x-mitre-tactic--b2a67b1e-913c-46f6-b219-048a90560bb9', 'x-mitre-tactic--97c8ff73-bd14-4b6c-ac32-3d91d2c41e3f', 'x-mitre-tactic--298fe907-7931-4fd2-8131-2814dd493134', 'x-mitre-tactic--ff048b6c-b872-4218-b68c-3735ebd1f024', 'x-mitre-tactic--77542f83-70d0-40c2-8a9d-ad2eb8b00279']}]
```
