### ISSUE TITLE
Multiple Source Names for the Same Thing (Mobile Attack)

### ISSUE THREAD

**Issue by r-joyce** [mitre/cti#13]
I'm parsing the JSON files of the attack, pre-attack, and mobile-attack data and part of my parsing I'm extracting the `external_id` from the `external_references` field. 

While I'm only interested in the IDs from you guys, so I have hard coded the source name that I am interested in, and in the case of mobile attack I noticed that there are _two_ source names for MITRE, both `mitre-mobile-attack` and `mitre-attack-mobile`. 

So to get everything, I'm checking for both of those, is there a difference between the two?

**Comment by jburns12** [comment]
Hi @r-joyce ....it looks like there are two source names where there should only be one. We will check this out to figure out the best way to remediate the issue. Thank you!

**Comment by jburns12** [comment]
Hey @r-joyce ...we just updated the GitHub repo as well as our TAXII server to only have mitre-mobile-attack for the source_name for all objects in ATT&CK for Mobile.

Please let us know if you continue to have any concerns about this. Thank you again!!
