### ISSUE TITLE
Inconsistency of ics-attack.json caused by missing identity object for created_by_ref

### ISSUE THREAD

**Issue by ksh7534** [mitre/cti#132]
There's no "The MITRE Corporation" identity object with id of "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5" in bundle for ics-attack, which results in an inconsistent STIX bundle.

It can be fixed by adding identity object for "The MITRE Corporation" to the bundle.

**Comment by isaisabel** [comment]
It looks like the file exists* in the filesystem, but it's just not present in the STIX bundle. I'll get that added.

* the filename (/ics-attack/identity/identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5.json.json) has the `.json` extension twice, which should also be fixed.
