### ISSUE TITLE
when capec v3.4

### ISSUE THREAD

**Issue by Kavan72** [mitre/cti#139]

**Comment by rpiazza** [comment]
Hi @Kavan72,

Currently the ATT&CK content is still using STIX 2.0.  When they transition to STIX 2.1, we will regenerate the CAPEC content for 3.4 using 2.1 also.

**Comment by rpiazza** [comment]
Actually, it seems the ATT&CK team would not be implementing that transition very soon.  I will try to get to refreshing CAPEC 3.4 in the near future.

**Comment by Kavan72** [comment]
hey @rpiazza,
ohh okay, thank for quick reply

**Comment by Kavan72** [comment]
and btw is there any client lib are available for capec like for ATT&CK we have `attackcti`.

**Comment by rpiazza** [comment]
We suggest you use cti-python-stix2 directly. See https://github.com/mitre/cti/blob/master/USAGE-CAPEC.md

**Comment by Kavan72** [comment]
yes, Current we are using this one.

**Comment by rpiazza** [comment]
All,
 
With the release of CAPEC 3.4 we have updated the CAPEC content as expressed as STIX at https://github.com/mitre/cti.
 
Thanks again for your interest and contributions to CAPEC!

**Comment by Kavan72** [comment]
great, thank you
