### ISSUE TITLE
502 Server Error: Bad Gateway for url: https://cti-taxii.mitre.org/taxii/

### ISSUE THREAD

**Issue by FFally** [mitre/cti#149]
Hi I am currently getting a 502 when trying to access https://cti-taxii.mitre.org/taxii/ ?

**Comment by isaisabel** [comment]
Hi @FFally,

We've had some unscheduled TAXII server outages recently which are the cause of that error. If you want to ensure you can access the dataset even when we have an outage, please refer to [the other methods of access](https://github.com/mitre/cti/blob/master/USAGE.md#access-from-github-via-requests) which are not reliant on that server.
