### ISSUE TITLE
v8.2 changes incomplete on TAXII server

### ISSUE THREAD

**Issue by sanason** [mitre/cti#155]
I am trying to pull ATT&CK v8.2 data from the TAXII server and it appears that the two techniques that were modified in v8.2 are out-of-date on the server.

On the website, [Additional Cloud Credentials](https://attack.mitre.org/techniques/T1098/001/) has version 2.1 but accessed via TAXII
```
src.query([
    Filter("external_references.external_id", "=", "T1098.001"),
    Filter("type", "=", "attack-pattern")
])[0])
```
the object returned has x_mitre_version 2.0.

Likewise, on the website, [Domain Policy Modification](https://attack.mitre.org/techniques/T1484/) has version 2.0 but accessed via TAXII, the x_mitre_version is 1.1.

Newly created objects appear to be correct, though I didn't check very carefully.

**Comment by sanason** [comment]
@isaisabel Today I re-ran our scripts that load data from TAXII and it appears that this problem has been fixed. Your doing or magic? In any case, thanks.

**Comment by isaisabel** [comment]
Hi @sanason,

We reloaded the data on the TAXII server a few weeks ago after seeing this issue, but I hadn't had time to actually test whether it fixed the inconsistency. Since you say it's fixed now I'll close it, thanks for following up!
