### ISSUE TITLE
Order of techniques of a tactic

### ISSUE THREAD

**Issue by rudyzzz** [mitre/cti#156]
Hello, I have noticed that function "get_tactic_techniques" from usage document returns techniques of tactic in different order than order used in Enterprise Matrix. In my project I would like to construct modified matrix, so I need them in this order. However, I haven't been able to figure out any way to do this, is there any please? Thanks in advance.

**Comment by isaisabel** [comment]
Techniques within a tactic are sorted alphabetically by name, and likewise sub-techniques within a technique are sorted alphabetically. It should be pretty easy to apply a python `sorted` function to the result to get the order.

You may also want to check out the code behind the matrices so you can get the layout correct (sub-techniques do complicate the layout quite a bit):
- [Matrix implemented in Angular](https://github.com/mitre-attack/attack-navigator/tree/master/nav-app/src/app/matrix/matrix-side)
- [Matrix implemented in Jinja](https://github.com/mitre-attack/attack-website/blob/master/attack-theme/templates/macros/matrix.html)

**Comment by rudyzzz** [comment]
Oh, I don't know how I missed that, sorry for quite stupid question, thanks for all the advice.
