### ISSUE TITLE
converts STIX 2.0 to 2.1

### ISSUE THREAD

**Issue by lizitong67** [mitre/cti#157]
How can I convert the CTI expressed with STIX 2.0 to STIX 2.1?

**Comment by isaisabel** [comment]
Hi @lizitong67,

We're going to be releasing a STIX 2.1 version of the dataset later this year (see #79). In the meantime, the method to convert is something like this:
- All SDOs will need a new `spec_version` field with the values `"2.1"`
    - the STIX bundles' `spec_version` will also need to be upgraded from `"2.0"` to `"2.1"`
- All malware type SDOs will require a new `is_family` field, which for ATT&CK will always be `true`

This conversion should be quite easy to do with a simple python script.

You can read more about the changes from STIX 2.0 to STIX 2.1 [in the STIX spec](https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_am3e79x6zc1p).
