### ISSUE TITLE
Antivirus blocking download

### ISSUE THREAD

**Issue by macarongbadessy** [mitre/cti#162]
Hello, 

I am getting a Trojan.privilegeEscalation when I tried to download ATT&CK-v8.2.zip. Any advice? I can always disabled my antivirus, but I don't want to do that. Is it safe?  Also, I need this version as I am halfway through a project with version 8. Thanks!

![image](https://user-images.githubusercontent.com/83777510/118708971-0936a480-b7e2-11eb-86ad-3f726d7d3880.png)

**Comment by isaisabel** [comment]
Hi @macarongbadessy,

This is probably the same issue as #76 and #162. Essentially there are a few code examples which are false positives with some antivirus software, specifically the detection section of _Server Software Component: [Web Shell](https://attack.mitre.org/techniques/T1505/003/)_ gets flagged sometimes:

![image](https://user-images.githubusercontent.com/28868888/118710326-22445300-b7ec-11eb-835d-94774ff019f9.png)

There's really nothing much we can do about it on our end.

**Comment by isaisabel** [comment]
So short answer: yes it should be safe to download the JSON, you're experiencing a false positive.
