### ISSUE TITLE
Some external references are missing in attack pattern

### ISSUE THREAD

**Issue by avshein** [mitre/cti#165]
Web page of technique https://attack.mitre.org/techniques/T1498/001 lists 3 references
```

- Preet Bharara, US Attorney. (2016, March 24). Retrieved April 23, 2019.
- Meintanis, S., Revuelto, V., Socha, K.. (2017, March 10). DDoS Overview and Response Guide. Retrieved April 24, 2019.
- Cisco. (n.d.). Detecting and Analyzing Network Threats With NetFlow. Retrieved April 25, 2019.

```
From other hand the corresponding attack-pattern
enterprise-attack/attack-pattern/attack-pattern--0bda01d5-4c1d-4062-8ee2-6872334383c3.json is missing
`Meintanis, S., Revuelto, V., Socha, K.. (2017, March 10). DDoS Overview and Response Guide. Retrieved April 24, 2019.`

Shouldn't the references be identical?

**Comment by isaisabel** [comment]
Hi @avshein,

References sections on the ATT&CK website include all external references which appear on the page, which includes not only the object itself but also its relationships. In this case the "missing" reference occurs on the mapping to M1037, and you can find the corresponding external reference on the corresponding [STIX relationship](https://github.com/mitre/cti/blob/master/enterprise-attack/relationship/relationship--52fcde3f-d3af-4785-940f-5856dd657455.json#L16-L22).
