### ISSUE TITLE
Version 8.0 is labeled as latest version on Github

### ISSUE THREAD

**Issue by rubinatorz** [mitre/cti#171]
Version 8.0 is labeled as latest on github:

![Screenshot 2021-06-25 at 12 23 29](https://user-images.githubusercontent.com/11735227/123410926-28c6a700-d5b0-11eb-8484-1cf6f5c2e24b.png)

I think this should be version 9.0, right?

**Comment by isaisabel** [comment]
Yes that's a bug, it should be version 9.0.

We discovered a bug in ATT&CK v8.0 when developing our new [attack-stix-data](https://github.com/mitre-attack/attack-stix-data) (STIX 2.1) repository and had to patch ATT&CK v8.0 about a week or two ago. Therefore the tag for ATT&CK v8.0 is newer than the tag for ATT&CK v9.0, and GitHub thinks it's the latest release. I will re-add the v8.0 tag but see if I can back-date it to when 8.0 was actually released which will hopefully fix this.

**Comment by isaisabel** [comment]
[Backdating the tag](https://stackoverflow.com/a/22838010) as explained here seems to have worked. The releases are now properly ordered and v9.0 is once again the latest release.

Thank you so much for pointing out this bug!
