### ISSUE TITLE
Both stix-capec.json for 2.0 and 2.1 stix are the same

### ISSUE THREAD

**Issue by SteliosZ** [mitre/cti#176]
Hello.

I've made a unit test that to check some things for the version 2.0 of stix-capec.json, which was initially alone.
Today, after almost 4 weeks of not running this test, it failed due to the missing link. 
At first glance, I noticed the url change, so I changed it and initially thought that this would fix my problem, and it did. 

Unit test was failing further down the line, so proper debugging was required. After some trial and error I noticed that both versions are the 2.1 version. Both files are the same, with the sole difference of the spec-version line.

I checked with the 'cmp' command in terminal, and because it seemed to easy, I cross-checked with a python script.

Thanks for your time and effort overall, I hope that you will fix this soon.

**Comment by rpiazza** [comment]
Hi @SteliosZ 

I did a review of both directories.  They seem to be up-to-date for version 3.5, and different.  For all entries, the content is basically the same, so the spec_version might be the only difference

Can you show me a specific example of why you think the content isn't different?

**Comment by SteliosZ** [comment]
Hello and thank you for your reply.

My test is checking the keys of every element of the bundle. It was failing because it found "new" keys, 
namely x_capec_child_of, x_capec_parent_of, x_capec_can_precede. 

I didn't run this test since 16/07 I think. When I saw the change in the repo (the split of 2.0 and 2.1 stix versions) I thought that those keys were just new additions in the 2.1 version of STIX.

Now that I read your reply, I think that my mistake is that the information I was testing was of 3.4 of CAPEC and now it's 3.5. 
The thing is that I cannot find a changelog that points out this change of keys in the bundle.

Excuse my confusion and thank you for your kind reply, but I have a hard time tracking those changes.

**Comment by rpiazza** [comment]
@SteliosZ 

You make a good point.  We should have documented the changes we made.  We will remedy this soon.  

I hope that the new data is useful for you.
