### ISSUE TITLE
Max Retries exceeded with https://cti-taxii.mitre.org/taxii/

### ISSUE THREAD

**Issue by fear-the-reaper** [mitre/cti#179]
I'm running this piece of code from the usage.md:
![image](https://user-images.githubusercontent.com/46054431/131118047-d20d24e5-3197-4767-a1e0-1ae38d870886.png)

but I keep getting this error:
![image](https://user-images.githubusercontent.com/46054431/131118142-5d45f926-1058-49fe-9432-d4aa7f9f5242.png)

the python version I'm using is 3.7.1

**Comment by isaisabel** [comment]
Hi @fear-the-reaper,

We had an unplanned TAXII server outage from 2–7am EST on August 27. That was almost definitely the cause of your connection trouble. The server should be back online and the code above looks like it should work if run now.
