### ISSUE TITLE
Is 'Has technique object' property for 'Software' available in ATT&CK STIX Content?

### ISSUE THREAD

**Issue by Cyb3rWard0g** [mitre/cti#18]
Good evening Team,

Is the **'Has technique object'** property available via TAXII?

**For example:**

Let's say I want to gather information about Software: Winnti.

If I go to https://attack.mitre.org/wiki/Software/S0141 , I can see the following:

![image](https://user-images.githubusercontent.com/9653181/40602594-2abf656a-6227-11e8-98da-5833245135fb.png)

I would like to gather the specific information/description of each technique associated with the Software:

![image](https://user-images.githubusercontent.com/9653181/40602705-8f9526d2-6227-11e8-844c-3c64f0a05190.png)

If I were using the legacy API, I would first pull all the 'Has technique object' values and then filter them by the specific software:

```
"[[Has technique object::+]]|?Has technique description#-ia|?Has technique object|limit=9999"
```
If I look at the **Property:Has technique object** page and look for "Winn", I  get the following:

https://attack.mitre.org/w/index.php?title=Property:Has_technique_object&limit=500&offset=2000&value=&from=&until=

![image](https://user-images.githubusercontent.com/9653181/40602994-98eccc84-6228-11e8-8863-2796ae1f6d32.png)

Then, if I click on the eye next to the name of the software, I get to the "Hast technique object" page of the specific technique associated with Software **Winnti**:

![image](https://user-images.githubusercontent.com/9653181/40602781-d6a4e4ae-6227-11e8-930a-3233c334c238.png)

This was very easy to do via the legacy API with the following line in the Invoke-ATTACKAPI:

https://github.com/Cyb3rWard0g/Invoke-ATTACKAPI/blob/master/Invoke-ATTACKAPI.ps1#L1068

However, with ATT&CK STIX content via TAXII, I cannot find those specific descriptions of techniques associated with Software (malware or tool). Is there a way available to get that information?

I was looking at the relationships and I dont know which relationships might work to gather that type of information.

Thank you in advance!

**Comment by Cyb3rWard0g** [comment]
So far, I can only use the Software original descriptions and use relationships defined to map:
Group -> tactics -> techniques -> software (When Available)

Group Winnit:

![image](https://user-images.githubusercontent.com/9653181/40603710-c29737d4-622a-11e8-927f-0a55ea204e4b.png)

I am replicating the same functionality as the PowerShell script I shared earlier and provide a similar output:

https://github.com/Cyb3rWard0g/ThreatHunter-Playbook/blob/master/adversary_attribution/Winnti%20Group.md

Thank you!

**Comment by jburns12** [comment]
Hey @Cyb3rWard0g ! This is a great question. The 'Has Technique Object?' property is available in the STIX content as a description on a relationship object. For your case, you'd be looking for relationships that have the source_ref that is the ID of the software (tool or malware) object. Here's an example of how to do that for the Winnti software:

```
from stix2 import TAXIICollectionSource, Filter
from stix2.utils import get_type_from_id
from taxii2client import Collection

# Establish TAXII2 Collection instance for Enterprise ATT&CK collection
collection = Collection("https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/")

# Supply the collection to TAXIICollection
tc_source = TAXIICollectionSource(collection)

def get_technique_software_descriptions(src, sw_stix_id):
    rels = [
        r for r in src.relationships(sw_stix_id, 'uses')
        if get_type_from_id(r.target_ref) in ['attack-pattern']
    ]

    return rels

def get_software_by_name(src, name):
    software = src.query([
        Filter("type", "=", "tool"),
        Filter("name", "=", name)
    ])
    if len(software) == 0:
        software = src.query([
            Filter("type", "=", "malware"),
            Filter("name", "=", name)
        ])
    return software

def get_technique_by_id(src, id):
    technique = src.query([
        Filter("id", "=", id)
    ])
    return technique

software = get_software_by_name(tc_source, "Winnti")[0]
rels = get_technique_software_descriptions(tc_source, software)
for rel in rels:
    print(rel["description"])
    print(rel["target_ref"])
    print(get_technique_by_id(tc_source, rel["target_ref"])[0]["name"])
```
You could replace the get_software_by_name with a get_software_by_id similar to get_technique_by_id here if you wanted to just loop through all of the software (tools/malware) to get the techniques used by each one and corresponding descriptions.

Regarding relationship objects, attack-patterns will always be found as a target_ref and intrusion-sets will always be found as a source_ref. Therefore, tools/malware can be found as either. That has helped me in remembering how to set up my code to grab the correct content.

I hope this is helpful, and thanks again!

**Comment by Cyb3rWard0g** [comment]
Hey @jburns12 !! omg lol how did I miss the relationship description property??. It was 3am already so it must have been the time hahaha. Thank you so much for all the information!! I appreciate the details and the example 👍 💯
