### ISSUE TITLE
ATT&CK API

### ISSUE THREAD

**Issue by patcollis34** [mitre/cti#2]
I'm trying to use the ATT&CK API and pull all information related to each group, pretty much pull this info: https://attack.mitre.org/wiki/Special:Browse/:Group-2FG0006 down through the API.  Using a query like this: [[Category:Group]]|?Has technique|?Has description|?Has ID|?Has alias|limit=9999 it pulls down most of the info but when trying to add either |?Uses software, |?Has software, |?Has software object.  I feel like I'm missing some syntax somewhere.

**Comment by johnwunder** [comment]
Hm, I end up making a similar query, the whole thing looks like this:

```
https://attack.mitre.org/api.php?action=ask&format=json&query=[[Category:Group]]|[[Has%20ID::G0018]]|?Has%20display%20name|?Has%20technique|?Has%20ID|?Has%20alias|?Has%20description|?Uses%20software|?Categories|?Citation%20reference|?Has%20contributor|limit=9999
```

Notice the key in there is "|?Uses software" (the space is encoded as %20). If you try that URL it should pull back what you're looking for.

The other thing you could do is use the JSON in this repository directly (`mitre-attack.json` file). The groups are intrusion sets, software is either malware or tool, and relationships will link them together (it's modeled as a node/link graph).

**Comment by johnwunder** [comment]
This issue has been open awhile, I'm going to close it. Please re-open or contact attack@mitre.org if you're still having issues.
