### ISSUE TITLE
Revoked-By Techniques

### ISSUE THREAD

**Issue by gothera** [mitre/cti#200]
After seeing https://github.com/mitre/cti/issues/24
I would have a question. Is it possible, in the future, that a technique that revoked(replaced) another to also be "revoked-by" another technique ?

Thank you

**Comment by adampennin** [comment]
Any technique marked as revoked should also have a revoked-by relationship pointing at the new technique. If a technique was removed without replacement it should be x_mitre_deprecated instead (https://github.com/mitre/cti/blob/master/USAGE.md#removing-revoked-and-deprecated-objects).
