### ISSUE TITLE
Alias of APT37 has a typo

### ISSUE THREAD

**Issue by Weimin-Wu** [mitre/cti#216]
"Richochet Chollima" should be "Ricochet Chollima". Only the url in line 80 is correct.

https://github.com/mitre/cti/blob/a89063049d8440b23100fc40e0cca06f748d0b8f/enterprise-attack/intrusion-set/intrusion-set--4a2ce82e-1a74-468a-a6fb-bbead541383c.json#L9

https://github.com/mitre/cti/blob/a89063049d8440b23100fc40e0cca06f748d0b8f/enterprise-attack/intrusion-set/intrusion-set--4a2ce82e-1a74-468a-a6fb-bbead541383c.json#L40-L41

https://github.com/mitre/cti/blob/a89063049d8440b23100fc40e0cca06f748d0b8f/enterprise-attack/intrusion-set/intrusion-set--4a2ce82e-1a74-468a-a6fb-bbead541383c.json#L79-L81

**Comment by jondricek** [comment]
Thank you for reporting this - we've got it addressed in our internal system and the fix will be incorporated into the next release
