### ISSUE TITLE
Missing Some Records in 'Data Sources'

### ISSUE THREAD

**Issue by Naveen6557** [mitre/cti#219]
Hi 

Some records are missing in 'Data Sources'.

i am using 'mitre-object.get_datasources(remove_revoked_deprecated=True)' method to pull all the Data Sources from 'enterprise-attack.json' file.

The above method is returning only 37 records where the UI is showing 41 records 

The below given records are missing 

<img width="1044" alt="Screenshot 2023-08-14 at 09 34 42" src="https://github.com/mitre/cti/assets/42464535/73b4a30e-f4eb-47a6-b3a2-5c7f39f61520">

<img width="756" alt="Screenshot 2023-08-14 at 09 34 52" src="https://github.com/mitre/cti/assets/42464535/5ae8dcc7-a2c4-4979-b5aa-b4fca2392bba">

<img width="1012" alt="Screenshot 2023-08-14 at 09 35 05" src="https://github.com/mitre/cti/assets/42464535/c816bc20-bbc1-479a-88be-dbd74321834b">

<img width="990" alt="Screenshot 2023-08-14 at 09 35 22" src="https://github.com/mitre/cti/assets/42464535/39a4ba1d-bc49-47db-a9eb-f5f5ce77f4c8">

Can any one help on this please 

Thank you

**Comment by clemiller** [comment]
Hi @Naveen6557,

The list of [Data Sources on the ATT&CK website](https://attack.mitre.org/datasources/) is the complete list of Data Sources in Enterprise, Mobile, and ICS (altogether there are 41). Enterprise contains only 37 Data Sources. The 4 Data Sources you've listed above have relationships only with Mobile (DS0041 & DS0042) or ICS (DS0039 & DS0040) techniques and are not a part of the Enterprise dataset. If you would like to retrieve all 41 listed Data Sources, you would need to call `get_datasources()` on Enterprise, Mobile, and ICS.
