### ISSUE TITLE
ATT&CK attack-patterns no longer have external_references to CAPEC

### ISSUE THREAD

**Issue by samwagg** [mitre/cti#221]
I noticed that all Techniques that have `external_references` to CAPEC have either been revoked or deprecated. Is it an intentional/systematic policy to no longer include CAPEC references in the ATT&CK dataset?

**Comment by adampennin** [comment]
They were removed in v13 of ATT&CK back in April and it's an oversight that this wasn't mentioned in the release notes. Those references will not be included in the future unless they're a part of citations in technique descriptions. The CAPEC team maintains their own mapping from CAPEC to ATT&CK, which is still in place.
