### ISSUE TITLE
Taxii server is down

### ISSUE THREAD

**Issue by jpferrero** [mitre/cti#230]
There is an issue trying to connect https://cti-taxii.mitre.org. Is there any issue with the server?

**Comment by jondricek** [comment]
It should be up and running again now.

**Comment by seansica** [comment]
@jpferrero Please consider using the newer TAXII 2.1 server instead. It's much more stable than the older TAXII 2.0 server. You can read more about it [here](https://medium.com/mitre-attack/introducing-taxii-2-1-and-a-fond-farewell-to-taxii-2-0-d9fca6ce4c58). cti-taxii.mitre.org will retire on Dec 18.
