### ISSUE TITLE
Identities and Markings across datasets

### ISSUE THREAD

**Issue by emmanvg** [mitre/cti#25]
Would it make sense to use a single `Identity` and `MarkingDefinition` across the four datasets since the have the same information? Currently we have:

- CAPEC
  - `identity--31f421d4-bb36-4dbf-9dfc-c116a91de14b`
  - `marking-definition--b345b2a9-b539-4d88-8a9a-1ebcc9f77507`

- Enterprise ATT&CK, Mobile ATT&CK, Pre ATT&CK
  - `identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5`
  - `marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168`

**Comment by jburns12** [comment]
That makes sense to me, but I'll defer to @rpiazza  and @johnwunder for this one.

**Comment by rpiazza** [comment]
Makes sense, but I'm not sure it is worth the effort.  Let me take a quick look...

**Comment by rpiazza** [comment]
One or the other converters (or both) could take command line arguments that contained the common identifiers to use.  However, the marking definitions are different - since CAPEC is funded by DHS. So for just the identity identifier, it probably isn't worth it.

**Comment by emmanvg** [comment]
You are right, the identity would be the only change.
