### ISSUE TITLE
Software (Malware and Tool) is missing platform information

### ISSUE THREAD

**Issue by johnwunder** [mitre/cti#26]
The website has Platform information for software: https://attack.mitre.org/wiki/Software/S0066

But, that property isn't being added to the structured STIX content. That should be fixed by adding an `x_mitre_platforms` custom property with that information.

**Comment by Cyb3rWard0g** [comment]
Good evening,

I hope you all had a great week. Would you mind providing an ETA on this??  Thank you in advance 👍

**Comment by johnwunder** [comment]
I'll take a look soon. We were thinking of waiting until our next content update, but since that's a ways off and this is a small fix to just software/tool I think we can get it out sooner, maybe next week.
