### ISSUE TITLE
[Question] Is there a way to query data source without dowloading it?

### ISSUE THREAD

**Issue by SofiaArancibia** [mitre/cti#39]
From [here](https://github.com/mitre/cti/blob/master/USAGE.md) I understand that in order to query MITRE matrix I need to download `enterprise-attack` data source (for instance). But how can I query the matrix without downloading anything?

**Comment by jburns12** [comment]
HI @SofiaArancibia - one option that doesn't require downloading the ATT&CK STIX content is querying our TAXII server instead. [This blog post](https://medium.com/mitre-attack/att-ck-content-available-in-stix-2-0-via-public-taxii-2-0-server-317e5c41e214) gives an example of how to do this using the stix2/taxii2client Python libraries. If you're just looking for the techniques in the enterprise matrix, you can just filter on attack-patterns as seen in that example.

If you aren't using Python, another thing you can do is send a GET request for the full set of raw domain STIX/JSON content found at https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json (these also can be found for ATT&CK for Mobile or PRE-ATT&CK). Then you can parse the ATT&CK content using whatever method you choose.

Hopefully this helps, but if you have any further questions please let us know!

**Comment by jburns12** [comment]
Closing as this appears to be resolved.
