### ISSUE TITLE
Incorrect id for Initial access tactic

### ISSUE THREAD

**Issue by smifun** [mitre/cti#43]
Hi
In `cti/enterprise-attack/x-mitre-tactic/x-mitre-tactic--ffd5bcee-6e16-4dd2-8eca-7b3beedf33ca.json` file I would expect that id will be consistent with file name and references from mitre-matrix. Instead it has id `x-mitre-tactic--0a93fd8e-4a83-4c15-8203-db290e5f2ac6` which is not referenced anywhere.

**Comment by jburns12** [comment]
Hi @smifun - thanks so much for bringing this to our attention.

You are correct, and we just updated the id in the file `cti/enterprise-attack/x-mitre-tactic/x-mitre-tactic--ffd5bcee-6e16-4dd2-8eca-7b3beedf33ca.json` to match the file name as well as the object as found in `enterprise-attack.json`.

We appreciate you taking the time to point this out!
