### ISSUE TITLE
APT28 had different intrusion ID's for mobile vs old attack

### ISSUE THREAD

**Issue by infosec-alchemist** [mitre/cti#5]
In the mobile attack, the intrusion set is intrusion-set--97685862-7ea4-40e8-a420-6bffc2292c1e for APT28.  However, the original ATTACK has a different intrusion set ID.

If they are both APT 28, then they should be the exact same data.

**Comment by johnwunder** [comment]
Yeah this is a bug, they should have the same ID and the same data.

**Comment by johnwunder** [comment]
This is fixed now, across both mobile ATT&CK and pre ATT&CK (both of which use the intrusion sets from enterprise ATT&CK)
