### ISSUE TITLE
Use of x_ properties and non x_ properties ?

### ISSUE THREAD

**Issue by StephenOTT** [mitre/cti#50]
Looking at the following:

https://github.com/mitre/cti/blob/master/enterprise-attack/x-mitre-tactic/x-mitre-tactic--2558fd61-8c75-4730-94c4-11926db2a263.json#L23

What is the history of having a custom object but still carry in x_ properties?  There seems to be mix of the usage between having x_ props and non-x_ props for a custom object.  So looking to get the logic so I can map https://github.com/StephenOTT/STIX-Java to support the parsing of the att&ck patterns. 

thanks

**Comment by isaisabel** [comment]
Hi @StephenOTT,

I don't actually know the official history of using custom objects with x_mitre properties. However, my guess is that we originally decided to use x_mitre properties with custom objects to respect the STIX common fields. 

Non x_mitre properties on our custom objects such as type, name, description, external_references, and so forth are defined in the STIX documentation as "[common properties](https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html#_Toc16070605)" — properties that all SDOs are allowed to have.

Therefore, it was presumably decided that any fields on our custom objects which are not common properties should start with the x_mitre prefix to differentiate them from the common properties.
