### ISSUE TITLE
S0310 doesn't exist in enterprise.json?

### ISSUE THREAD

**Issue by HamptonJ** [mitre/cti#51]
I noticed that I wasn't seeing all of the malware objects in enterprise.json that exist on the attack mitre website, such as: https://attack.mitre.org/software/S0310/
Is there an estimated time for the next update?
Thanks!

**Comment by jburns12** [comment]
Hi @HamptonJ - you can actually find that malware object in the mobile-attack.json bundled file in the mobile-attack directory since this is Android malware. Thanks!
