### ISSUE TITLE
Mitigation for T1500 has an incorrect reference to technique

### ISSUE THREAD

**Issue by khanf9** [mitre/cti#52]
Hello,
I noticed that the external reference for recently added Compile After Delivery Mitigation, points to an invalid technique.

  "external_id": "T1502",
   "source_name": "mitre-attack",
   "url": "https://attack.mitre.org/techniques/T1502" 

Should be:

    "external_id": "T1500",
    "source_name": "mitre-attack",
     "url": "https://attack.mitre.org/techniques/T1500"

Reference:
https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json

**Comment by jburns12** [comment]
Hi @khanf9  - thanks for catching this! This was due to an issue in our ID'ing process for the latest ATT&CK content update. We've updated this repo and the TAXII server to reflect the proper external reference for this mitigation.
