### ISSUE TITLE
Mitigation for T1033 has an incorrect reference to technique

### ISSUE THREAD

**Issue by humbertcostas** [mitre/cti#53]
Analyzing an enterprise object, I noticed a mistake on "external_references" node in [this](https://github.com/mitre/cti/blob/master/enterprise-attack/course-of-action/course-of-action--16f144e4-c780-4ed2-98b4-55d14e2dfa44.json) JSON file.

```{js}
...
{
  "external_id": "T1482",
  "source_name": "mitre-attack",
  "url": "https://attack.mitre.org/techniques/T1482"
}
...
"name": "System Owner/User Discovery Mitigation",
...
```

Reading mitigation text on attack.mitre.org for [T1482 Domain Trust Discovery](https://attack.mitre.org/techniques/T1482/) and [T1033 System Owner/User Discovery](https://attack.mitre.org/techniques/T1033/), I suppose that should be:

```{js}
{
  "external_id": "T1033",
  "source_name": "mitre-attack",
  "url": "https://attack.mitre.org/techniques/T1033"
}
```

**Comment by jburns12** [comment]
Hi @humbertcostas - thanks so much for bringing this to our attention! We've pushed an update to this repo and our TAXII server to fix the issue and change the external reference to T1033.

As a heads up, in the near future the Enterprise ATT&CK `course-of-action` objects will be ID'ed separately from their corresponding techniques, similar to how the Mobile mitigations are currently handled. We'll make sure to release info on how to handle to this when the time comes.

Thanks again!
