### ISSUE TITLE
Attribute x_mitre_data_sources missing

### ISSUE THREAD

**Issue by crud3** [mitre/cti#59]
Hi all,

I just noticed that the `x_mitre_data_sources` attribute is missing in four techniques in the `enterprise-attack` data. This leads to an error when trying to access this attribute in every technique: `'AttackPattern' object has no attribute 'x_mitre_data_sources'`

Should every technique contain the `x_mitre_data_sources` attribute, or is it intentional/okay if it is missing in some?

The techniques where the attribute is missing are: 

- attack-pattern--348f1eef-964b-4eb6-bb53-69b3dcb0c643
Peripheral Device Discovery
- attack-pattern--6fb6408c-0db3-41d9-a3a1-a32e5f16454e
Gatekeeper Bypass
- attack-pattern--451a9977-d255-43c9-b431-66de80130c8c
Port Knocking
- attack-pattern--6a3be63a-64c5-4678-a036-03ff8fc35300
Re-opened Applications

**Comment by jburns12** [comment]
Hi @crud - thanks for the question!

It's not mandatory that every technique has this particular attribute, but we do plan to add data sources to these four techniques in the next ATT&CK technique update. I'd recommend putting in a conditional to check for whether or not this attribute exists - we did something similar in our Python code that generates the ATT&CK website from STIX.
