### ISSUE TITLE
The STIX 2.0 spec does not show "modified" as a property for Sightings, but the example does.

### ISSUE THREAD

**Issue by nidhisneh** [mitre/cti#61]
http://docs.oasis-open.org/cti/stix/v2.0/cs01/part2-stix-objects/stix-v2.0-cs01-part2-stix-objects.html#_Toc496714343
see Section 3.2

**Comment by isaisabel** [comment]
i @nidhisneh,

`modified` is a common property of all STIX objects, and is included in the first section of 3.2.1, highlighted below:

<img width="1640" alt="Screen Shot 2019-08-20 at 2 41 07 PM" src="https://user-images.githubusercontent.com/28868888/63374869-b43dd400-c358-11e9-87b9-8091031c4f68.png">

**Comment by nidhisneh** [comment]
I did see that - Thanks.

**Comment by nidhisneh** [comment]
Ack.
