### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by utkuaysev** [mitre/cti#62]
Hello,
When I run below script from this link :
https://medium.com/mitre-attack/att-ck-content-available-in-stix-2-0-via-public-taxii-2-0-server-317e5c41e214 
I got 502 Server Error Bad Gateway.

    from stix2 import TAXIICollectionSource 
    from taxii2client import Server
    # Instantiate server and get API Root
    server = Server("https://cti-taxii.mitre.org/taxii/")
    api_root = server.api_roots[0]

    # Print name and ID of all ATT&CK technology-domains available as collections
    for collection in api_root.collections:
        print(collection.title + ": " + collection.id)

Can you help me about this issue?
Thanks

**Comment by isaisabel** [comment]
Hi @utkuaysev,

We had an outage yesterday, probably while you were trying to connect. Can you try running the script again to see if it works now?

**Comment by utkuaysev** [comment]
Yes it is working now. thank you.I wonder that is these collections updating when new intelligence comes?

**Comment by isaisabel** [comment]
Hi @utkuaysev,

We update this repo (and the TAXII server) with new data on average thrice yearly. You can see our update log here: https://attack.mitre.org/resources/updates/

Does this answer your question?

**Comment by utkuaysev** [comment]
Hello @isaisabel 
Yes.Thank you for your assistance.
