### ISSUE TITLE
Migration of the old mitigation ID to the new one

### ISSUE THREAD

**Issue by fsnormand** [mitre/cti#81]
Hello, 
In the external_references of course_of_action, the json has the old Mitre id.
Have you include in your roadmap to change to the new mitigation id ?
Best regards
François

**Comment by isaisabel** [comment]
Hi @fsnormand,

I'm not quite sure what you're referring to when you say "old MITRE ID." Could you post an example?

Thanks!

**Comment by fsnormand** [comment]
Yes sorry my message have not enough details. 
old mitigation mitre id : 
                {
                    "source_name": "mitre-attack",
                    "url": "https://attack.mitre.org/mitigations/T1085",
                    "external_id": "T1085"
                },
Now the mitigation ID starts by "M"

Thanks!

**Comment by isaisabel** [comment]
Hi @fsnormand,

Those are old, deprecated mitigations that were replaced in July 2019. They're marked with a field `x_mitre_deprecated` to convey that they should no longer be used. 

Please see this response for more on the mitigations refactor and how that affected the data on this repo: https://github.com/mitre/cti/issues/60#issuecomment-517267745
