### ISSUE TITLE
relationship type Procedure is not preserved in STIX during the port from MITRE

### ISSUE THREAD

**Issue by Radu3000** [mitre/cti#82]
I am looking at this mitre page https://attack.mitre.org/techniques/T1114/

So it clearly show Procedure Examples as a table.

However the following relationship does not indicate that is is of type "Procedure"
 ```
{
            "type": "relationship",
            "target_ref": "attack-pattern--1608f3e1-598a-42f4-a01a-2e252e81728f",
            "description": "[APT1](https://attack.mitre.org/groups/G0006) uses two utilities, GETMAIL and MAPIGET, to steal email. GETMAIL extracts emails from archived Outlook .pst files, and MAPIGET steals email still on Exchange servers that has not yet been archived.",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "created": "2017-05-31T21:33:27.035Z",
            "id": "relationship--757bed64-558b-4ea7-84b9-b82d8b23f9b2",
            "source_ref": "intrusion-set--6a2e693f-24e5-451a-9f88-b36a108e5662",
            "modified": "2019-08-20T13:08:13.221Z",
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "external_references": [
                {
                    "description": "Mandiant. (n.d.). APT1 Exposing One of China\u2019s Cyber Espionage Units. Retrieved July 18, 2016.",
                    "source_name": "Mandiant APT1",
                    "url": "https://www.fireeye.com/content/dam/fireeye-www/services/pdfs/mandiant-apt1-report.pdf"
                }
            ],
            "relationship_type": "uses"
        }
```

- Has this been lost while in this feed?
https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json

**Comment by isaisabel** [comment]
Hi @Radu3000,

You're correct that the word `procedure` doesn't appear anywhere explicitly in the STIX relationship. It's basically just a label we apply on the ATT&CK website side of things.

"Procedures" on the ATT&CK website are represented in the STIX on this repository as relationship of type `uses`, where the `target_ref` is an `attack-pattern` (the STIX term for technique). `uses` is a [default STIX relationship type](https://docs.oasis-open.org/cti/stix/v2.0/csprd01/part2-stix-objects/stix-v2.0-csprd01-part2-stix-objects.html#_Toc476230970). We do sometimes break from STIX conventions, e.g when adding `x_mitre_` properties or types, but we use STIX defaults wherever possible.

Procedures include both groups and software, e.g T1114 (which you linked) includes procedure examples of both APT1 (a group, AKA an `intrusion-set` in STIX) and SeaDuke (a software, in this case a `malware` in STIX — software in ATT&CK can be of STIX types `malware` or `tool`).

**Comment by Radu3000** [comment]
Ouch that hurts!  TTP lost its "P" leg while crossing the street from MITRE buiding to STIX building ... :/

Yes - "uses" is so generic and simple but it doped important info.

- So, what was the intent for dropping this info besides simplicity?  

- Any desire to restore that essential part for threat analitic work?

**Comment by isaisabel** [comment]
I don't believe anything is actually lost in the current representation. Every relationship of type `uses` targeting an attack-pattern is considered a procedure. All that's missing is the word "procedure."

[The ATT&CK website is built solely from data on this repo](https://github.com/mitre-attack/attack-website). The resource pages and a few other ancillary pages are added, but the contents of a given technique, tactic, matrix, group, etc page is pulled entirely from the data on MITRE/CTI. There's nothing extra added there for procedures. It's just a naming convention.

**Comment by Radu3000** [comment]
@isaisabel - that helps a lot!  In that case "uses" == "hasProcedure" - all the time, right?

**Comment by isaisabel** [comment]
Yes, each relationship of type `uses` targeting a technique is what represents a "procedure example." So if there is a relationship of type `uses` targeting a given technique, you could say that the technique has a procedure.

**Comment by isaisabel** [comment]
Also, the procedure examples in our dataset are not exhaustive (thus the word "example"). Just because a technique only has one or two procedure examples doesn't mean that there aren't more groups/software using the technique.

**Comment by isaisabel** [comment]
That's not to say that we don't aim to accurately represent breadth of a technique's usage  as accurately as possible, but we obviously can't report on technique usages "in the wild" that we don't know about.

**Comment by Radu3000** [comment]
@isaisabel - your last three response posts help a lot - thank you!

So - TTP didn't loose its leg after all ;) !  In fact it will be gaining one more leg - Sub-Technique - which I yet to better understand - studying faq and beta site now...
