### ISSUE TITLE
enterprise-attack failing schema validation

### ISSUE THREAD

**Issue by apowers313** [mitre/cti#88]
Apparently the `spec_version` property is mandatory for all objects per [STIX 2.0](http://docs.oasis-open.org/cti/stix/v2.0/stix-v2.0-part1-stix-core.html) Section 5.1, which prevents `enterprise-attack.json` from validating against [this schema](https://github.com/oasis-open/cti-stix2-json-schemas).

**Comment by apowers313** [comment]
The `bundle` SDO also requires `created` and `modified` properties to pass validation.

**Comment by isaisabel** [comment]
Hi @apowers313,

`enterprise-attack.json`, and all of our other _bundles_, do have the spec_version property:

![image](https://user-images.githubusercontent.com/28868888/85282128-33100b80-b459-11ea-82e1-db3859119b5e.png)

[The documentation for STIX Objects](https://docs.oasis-open.org/cti/stix/v2.0/cs01/part2-stix-objects/stix-v2.0-cs01-part2-stix-objects.html#_Toc496714300) doesn't mention that `spec_version` is mandatory on any SDOs themselves, only the bundle. `spec_version` doesn't actually show up anywhere in the document for STIX objects.

Regarding `created` and `modified`, they aren't mentioned as required fields in [the bundle spec](https://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_Toc496709293): 

![image](https://user-images.githubusercontent.com/28868888/85282276-79656a80-b459-11ea-89ee-38904ea456c4.png)

The stix2-json-schemas repo you linked is implemented to check against the STIX 2.1 spec. Our data is built according to the STIX2.0 spec, which explains the issues. If you check out [the stix2.0 branch](https://github.com/oasis-open/cti-stix2-json-schemas/tree/stix2.0) of the validator repo it will probably work better.

**Comment by apowers313** [comment]
Thanks, my mistake -- you're right that running against `stix2.0` works so much better.
