### ISSUE TITLE
url missing for SanDisk SMART external_references

### ISSUE THREAD

**Issue by Radu3000** [mitre/cti#89]
In the enterprise-attack.json url is missing in this fragment:
```
                {
                    "source_name": "SanDisk SMART",
                    "description": "SanDisk. (n.d.). Self-Monitoring, Analysis and Reporting Technology (S.M.A.R.T.). Retrieved October 2, 2018."
                }
```
- Is that really missing or just not available?

Regards,
Radu

**Comment by isaisabel** [comment]
Hi @Radu3000,

While the majority of our external references have associated URLs, we aren't always able to include a URL depending on the availability of the original source. The `url` field is marked as optional on the [STIX External References spec](https://docs.oasis-open.org/cti/stix/v2.0/csprd01/part1-stix-core/stix-v2.0-csprd01-part1-stix-core.html#_Toc476227306).
