### ISSUE TITLE
Trailing whitespace in URLs?

### ISSUE THREAD

**Issue by apowers313** [mitre/cti#90]
This is a bit pedantic: there are a couple dozen URLs in the `enterprise-matrix.json` that have trailing whitespace, such as `"url": "https://www.virustotal.com/en/faq/ "` on line 1214. Strictly speaking, this doesn't meet the ABNF definition of a URI of [RFC 3986](https://tools.ietf.org/html/rfc3986#page-50).

Would you guys accept a pull request to clean those up? Or is that not worth bothering with?

**Comment by isaisabel** [comment]
Hi @apowers313,

In order to propagate corrections to all parts of the ATT&CK infrastructure we cannot accept pull requests to the data on this repository. I'll leave this issue open so that we can remember to clean the URLs up when we have time.

Thanks!

**Comment by apowers313** [comment]
Thanks! Note that `mobile-attack.json` also has some malformed URLs with unicode in the middle of them (the STIX spec points to RFC3986 for external-reference URLs, which doesn't allow unicode):

`https://www.zscaler.com/blogs/research/super-mario-run-malware-2-\u2013-droidjack-rat`

**Comment by isaisabel** [comment]
Just following up to say that the three occurrences of urls with leading and trailing whitespace in Enterprise will be fixed for the next release (see also #111). 

We still need to look at the unicode issue in the zscaler paper, and check the mobile dataset for whitespace issues. Therefore I'm leaving this issue open.

**Comment by isaisabel** [comment]
With ATT&CK v8.0 now released I'm closing this issue. If you notice any additional trailing whitespace issues in the new dataset we can reopen.
