### ISSUE TITLE
Deprecate the pre-ATT&CK domain

### ISSUE THREAD

**Issue by isaisabel** [mitre/cti#96]
With the next release of ATT&CK, the pre-ATT&CK domain is being migrated into new tactics under the enterprise domain. The pre-ATT&CK data on this repository should be removed via the following method:
- When the migration occurs:
    - all data in the pre-ATT&CK domain which is not already deprecated or revoked should be marked as deprecated. A paragraph should be prepended to all description fields explaining the migration.
    - Add a README within the `pre-attack` directory explaining the migration.
    - Update the USAGE document to remove pre-ATT&CK guidance.
- 6 months after the migration, remove the pre-ATT&CK data and documentation from this repository entirely. It will still be accessible by checking out earlier commits or tagged releases for users who wish to access the old content.

**Comment by isaisabel** [comment]
For the TAXII server, the pre-attack collection description should be updated equivalently to the README within the pre-attack directory. When the data is removed from this repo, we should delete the collection from the TAXII server altogether.

**Comment by dfirence** [comment]
@isaisabel 

What is the ETA for this migration, pleaseB

**Comment by isaisabel** [comment]
@dfirence The most specificity I can give you is "sometime this year." Please see the [2020 ATT&CK Roadmap](https://medium.com/mitre-attack/2020-attack-roadmap-4820d30b38ba) for more details.

**Comment by grimlock81** [comment]
I appreciate this isn't the most appropriate place for this question, but I'm finding it hard to find the information anywhere else on the web.

In the referenced pull request https://github.com/mitre/cti/pull/116 it is mentioned that ATT&CK version 8 is upcoming. Where can I find information on version 8 such as release dates and the finer details what's changed (besides removing pre-attack and adding ICS). Thanks.

**Comment by isaisabel** [comment]
Hi @grimlock81,

We don't typically announce release dates ahead of time in case something changes last minute and we have to reschedule. However, I think it would be a safe assumption on your end that it should be happening pretty soon given that we're currently staging documentation for the release.

In terms of what is changing in the release, we also don't publish the [detailed release notes](https://attack.mitre.org/resources/updates/) ahead of time. Typically the best place to see our broad future plans would be to read documents like our [2020 ATT&CK roadmap](https://medium.com/mitre-attack/2020-attack-roadmap-4820d30b38ba), keeping an eye on [our twitter](https://twitter.com/MITREattack), or watching our issue trackers (which you already seem to be doing).

**Comment by grimlock81** [comment]
Thank you for the information @isaisabel 

I look forward to the release.

**Comment by isaisabel** [comment]
This change has been released as part of ATT&CK v8.0. The rest of the infrastructure (website, Navigator, etc) will be updating to reflect the change later today.
