### ISSUE TITLE
Invalid external reference in Attack Patterns

### ISSUE THREAD

**Issue by eiyuki** [mitre/cti#98]
[T1574.002](https://github.com/mitre/cti/blob/master/enterprise-attack/attack-pattern/attack-pattern--e64c62cf-9cd7-4a14-94ec-cdaac43ab44b.json)

> [X] attack-pattern--e64c62cf-9cd7-4a14-94ec-cdaac43ab44b: external_references[1]: If the external reference is a CVE, 'source_name' must be 'cve' and 'external_id' must be in the CVE format (CVE-YYYY-NNNN+). If the external reference is a CAPEC, 'source_name' must be 'capec' and 'external_id' must be in the CAPEC format (CAPEC-N+). If the external reference is neither, it must contain the 'source_name' property and at least one of the 'external_id', 'url', or 'description' properties.

[T1574.010](https://github.com/mitre/cti/blob/master/enterprise-attack/attack-pattern/attack-pattern--9e8b28c9-35fe-48ac-a14d-e6cc032dcbcd.json)

> [X] attack-pattern--9e8b28c9-35fe-48ac-a14d-e6cc032dcbcd: external_references[0]: If the external reference is a CVE, 'source_name' must be 'cve' and 'external_id' must be in the CVE format (CVE-YYYY-NNNN+). If the external reference is a CAPEC, 'source_name' must be 'capec' and 'external_id' must be in the CAPEC format (CAPEC-N+). If the external reference is neither, it must contain the 'source_name' property and at least one of the 'external_id', 'url', or 'description' properties.

Have invalid external references to CAPECs when run through the cti-stix-validator. The linked page appears to be a 404.

It would be good to clean this up, as some tools that rely on the cti-stix-validator will not process an otherwise valid file.

**Comment by isaisabel** [comment]
It looks like this has been fixed in a release of ATT&CK since the issue was originally opened. If still relevant please feel free to reopen it.
